spring:
  application:
    name: dm-service
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      configurations: default

  datasource:
    url: jdbc:mysql://localhost:3306/DM_DB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
