server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: search-service
          uri: lb://SEARCH_SERVICE
          predicates:
            - Path=/search-service/**
        - id: usertimeline-service
          uri: lb://USERTIMELINE-SERVICE
          predicates:
            - Path=/usertimeline-service/**
        - id: user-service
          uri: lb://USER_SERVICE
          predicates:
            - Path=/user-service/**
        - id: dm-service
          uri: http://localhost:8084/
          predicates:
            - Path=/dm-service/**
        - id: hometimeline-service
          uri: lb://HOMETIMELINE-SERVICE
          predicates:
            - Path=/hometimeline-service/**
        - id: tweet-service
          uri: lb://TWEET-SERVICE
          predicates:
            - Path=/tweet-service/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    discovery:
      enabled: true
