spring:
  application:
    name: DM-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://H9:H9@queen.wxjtd.mongodb.net/Twitter?retryWrites=true&w=majority
      db: Twitter
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      configurations: default




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
