server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: search-service
          uri: http://localhost:8081/
          predicates:
            - Path=/search-service/**
        - id: usertimeline-service
          uri: http://localhost:8082/
          predicates:
            - Path=/usertimeline-service/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    discovery:
      enabled: true
